apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  # POZOR: Zameniaj tieto hodnoty za tvoje
  # DB URL: psql-fsa-<your-prefix>.postgres.database.azure.com
  # DB Username: fsaadmin
  # DB Password: Získaj od školiteľa
  #
  # Ako zakódovať: [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("<hodnota>"))
  db_username: "fsaadmin"
  db_password: "P@ssword12345!"
  db_url: "psql-fsa-vojtkom.postgres.database.azure.com"

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  # Keycloak Username: admin
  # Keycloak Password: admin
  kc_username: "admin"
  kc_password: "admin"

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: "glrt-HnuNXKuK2X-OGSltc-CX0mc6bgpvOjEKdDoyCnU6OA8.01.1719ci742"

