apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventfindr-be
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventfindr-be
  template:
    metadata:
      labels:
        app: eventfindr-be
    spec:
      containers:
        - name: eventfindr-be
          # Pred produkcnym deployom nastav vlastny ACR registry a idealne immutable image tag.
          image: acrfsavojtkom.azurecr.io/fsa-eventfindr-backend:latest
          imagePullPolicy: Always
          env:
            # Databazove udaje prichadzaju iba z Kubernetes Secretu.
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_password
            # Keycloak URL musi presne sediet s issuerom v tokene.
            - name: ISSUER_URI
              value: https://keycloak.20.223.129.102.nip.io/realms/EventfindR
            - name: JWT_URI
              value: https://keycloak.20.223.129.102.nip.io/realms/EventfindR/protocol/openid-connect/certs
            - name: JAVA_OPTS
              value: >-
                -Dspring.profiles.active=keycloak
                -Dspring.datasource.url=jdbc:postgresql://${DB_URL}:5432/fsa-db
                -Dspring.datasource.username=${DB_USERNAME}
                -Dspring.datasource.password=${DB_PASSWORD}
                -Dspring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}
                -Dspring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_URI}
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: media-storage
              mountPath: /application/media-storage
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: eventfindr-media-storage
